fix(ci): Overwrite wix install if exists
Since we moved these to self-hosted runners, wix may already be
installed so we should overwrite it.

I think this should be moved to the image build, but this should fix it
for now.

Failure:

```
Run mkdir -p /c/wix
Archive:  wix-binaries.zip
replace x86/burn.exe? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)
Error: Process completed with exit code 1.
```

https://github.com/timberio/vector/runs/3577882554?check_suite_focus=true

Signed-off-by: Jesse Szwedko <jesse@szwedko.me>