chore(dev): upgrade to Rust 2024 edition (#23522)
* chore(dev): upgrade to Rust 2024 edition

* cargo clippy --fix

* bump to 2024

* fixes and updates

* cargo fmt --all

* fmt

* more fixes

* more fixes

* Update src/sinks/socket.rs

Co-authored-by: Thomas <thomas.schneider@datadoghq.com>

* ran cargo fmt

* change edition in rustfmt

* ran cargo fmt

* ran cargo fmt

* address reporter future return type clippy failure

* ran cargo fmt

* events check

* ran cargo fmt

* running.rs changes

* upgrade cargo-deb

* ran cargo fmt

* fix

* ran cargo fmt

* cargo-deb override

* older cargo-deb

* downgrade cargo-deb

* fix one windows failure

* fix windows error[E0521]

---------

Co-authored-by: Thomas <thomas.schneider@datadoghq.com>