Compare floating points with approximate equality
In https://github.com/timberio/vector/pull/7522/checks?check_run_id=2632747234
we observed test failure because:

```
---- sinks::util::adaptive_concurrency::service::tests::increases_limit stdout ----
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `1.001`,
 right: `1.0`', src/sinks/util/adaptive_concurrency/service.rs:281:9
```

`assert_eq` is a mixed bag when testing for equality of floating points. The
approx crate, which we already use, takes into account the nature of floats in
its assertions.

That said, I'm not totally sure if this is a "floating points do unexpected
things" issue or a bug manifesting as what looks like a floating point
weirdness. Still, introducing approx here strikes me as a positive.

Signed-off-by: Brian L. Troutwine <brian@troutwine.us>