chore(ci): Fix nextest / rustup dll issue (#20544)
Workaround for issue in nextest caused by a change in rustup:
https://github.com/nextest-rs/nextest/issues/1493

Fixes:

```
error: creating test list failed

Caused by:
  for `vector-config-macros`, command
  `'C:\a\vector\vector\target\debug\deps\vector_config_macros-4fc11cf764d99dff.exe' --list --format
  terse` exited with code 0xc0000135: The specified module could not be found. (os error 126)
```

Signed-off-by: Jesse Szwedko <jesse.szwedko@datadoghq.com>